# Generated by Django 2.1.4 on 2019-01-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trainee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
