# Generated by Django 2.1.4 on 2019-01-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190102_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='cv',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
