# Generated by Django 2.1.4 on 2019-01-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_trainee_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='cv',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
